steps:
  # Build the docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - '$LOCATION-docker.pkg.dev/$PROJECT_ID/${ARTIFACTS_REPO}/backend'
      - '.'

  # Push the docker image to the Google Artifacts Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - '$LOCATION-docker.pkg.dev/$PROJECT_ID/${ARTIFACTS_REPO}/backend'

  # Deploy to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: 
      - 'gcloud'
      - 'run'
      - 'deploy'
      - '${ARTIFACTS_REPO}-backend'
      - '--image=$LOCATION-docker.pkg.dev/$PROJECT_ID/${ARTIFACTS_REPO}/backend'
      - '--platform=managed'
      - '--region=$LOCATION'

substitutions:
  ARTIFACTS_REPO: 'safe-qr-codes'
